# This is a basic workflow to help you get started with Actions
name: build docker image
# Controls when the action will run.
on:
  workflow_call:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      image:
        description: "image name"
        required: true
      repFolder:
        description: "rep folder"
        required: true
      context:
        description: "build context"
        required: true
      dockerfile:
        description: "dockerfile"
        required: true

env:
  TZ: Asia/Shanghai

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run pre-script
        run: . ${{ inputs.repFolder }}/install.sh

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.repFolder }}/rep/${{ inputs.context }}
          file: ${{ inputs.repFolder }}/rep/${{ inputs.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ inputs.image }}:${{ steps.date.outputs.today }}
            ${{ inputs.image }}:latest
